#ifndef KERNELS_H
#define KERNELS_H

const char * bitonic_sort_kernel_source  =
"__kernel                                                    "
"\n void _kbitonic_sort_kernel(                          		 "
"\n             __global int *input_ptr,                   	"
"\n             const unsigned int stage,                   "
"\n             const int passOfStage)                       "
"\n {                                        "
"\n                                          "
"\n      unsigned int  threadId = get_global_id(0);   "
"\n      unsigned int  pairDistance = 1 << (stage - passOfStage);   "
"\n      unsigned int  blockWidth = 2 * pairDistance;    "
"\n      unsigned int  temp;  "
"\n                                                           "
"\n      int compareResult;                                      "
"\n      unsigned int  leftId = (threadId & (pairDistance - 1)) + (threadId >> (stage - passOfStage) ) * blockWidth;  " 
"\n      unsigned int  rightId = leftId + pairDistance;   " 
"\n         " 
"\n      int leftElement, rightElement;  " 
"\n    	 int greater, lesser;  " 
"\n      leftElement = input_ptr[leftId]; " 
"\n      rightElement = input_ptr[rightId]; " 
"\n       " 
"\n      unsigned int sameDirectionBlockWidth = threadId >> stage;    " 
"\n      unsigned int sameDirection = sameDirectionBlockWidth & 0x1; " 
"\n       " 
"\n      temp = sameDirection ? rightId : temp; " 
"\n      rightId = sameDirection ? leftId : rightId; " 
"\n      leftId = sameDirection ? temp : leftId; " 
"\n       " 
"\n      compareResult = (leftElement < rightElement); " 
"\n       " 
"\n      greater = compareResult ? rightElement : leftElement; " 
"\n      lesser = compareResult ? leftElement : rightElement; " 
"\n       " 
"\n      input_ptr[leftId] = lesser; " 
"\n      input_ptr[rightId] = greater; " 
"\n }     " 
; 
 

//The bitonic sort kernel does an ascending sort 
const char * original_kernel_source = 
" __kernel                                                      "
" \n void _kbitonic_sort_kernel(	                              "
" \n 			__global int * input_ptr,                             "
" \n     	const uint stage,                                     "
" \n     	const uint passOfStage )                              "
" \n {                                                          "
" \n     uint threadId = get_global_id(0);                      "
" \n     uint pairDistance = 1 << (stage - passOfStage);        "
" \n     uint blockWidth = 2 * pairDistance;                    "
" \n     uint temp;                                             "
" \n     bool compareResult;                                    "
" \n     uint leftId = (threadId & (pairDistance -1))           "
"          + (threadId >> (stage - passOfStage) ) * blockWidth; "
" \n     uint rightId = leftId + pairDistance;                  "
" \n                                                            "
" \n     DATA_TYPE leftElement, rightElement;                   "
" \n     DATA_TYPE greater, lesser;                             "
" \n     leftElement = input_ptr[leftId];                       "
" \n     rightElement = input_ptr[rightId];                     "
" \n                                                            "
" \n     uint sameDirectionBlockWidth = threadId >> stage;      "
" \n     uint sameDirection = sameDirectionBlockWidth & 0x1;    "
" \n                                                            "
" \n     temp = sameDirection ? rightId : temp;                 "
" \n     rightId = sameDirection	? leftId : rightId;           "
" \n     leftId = sameDirection ? temp : leftId;                "
" \n                                                            "
" \n     compareResult = (leftElement < rightElement) ;         "
" \n                                                            "
" \n     greater = compareResult ? rightElement : leftElement;  "
" \n     lesser= compareResult ? leftElement : rightElement;    "
" \n                                                            "
" \n     input_ptr[leftId] = lesser;                            "
" \n     input_ptr[rightId] = greater;                          "
" \n }                                                          "
;


#endif

